### ISSUE TITLE
Future inserts/updates

### ISSUE THREAD

**Issue by bhavinkamani** [leoasis/activerecord-futures#10]
This is really useful. Thanks for your contribution.

Is it possible to extend this for inserts and updates. I am working on a project where often we have to fire multiple inserts to setup test data. This often causes the test to run very slow. 

Firing multiple inserts or updates in one round trip will make it pretty fast..

**Comment by leoasis** [comment]
Thanks for being interested in this, @bhavinkamani.

As for the issue, the scope of this gem is to just provide query batching, not inserts and deletes. For that, you already have existing gems, like https://github.com/zdennis/activerecord-import.

Also, the strategy to do so would be very different to implement, so it is not and extension per se. As you usually will need bulk insertion in different places than where you need query batching, it is ok to have separate gems to do each task in my opinion.

**Comment by bhavinkamani** [comment]
Thank you for your reply @leoasis. I have been using `activerecord-import`. While it serves my purpose in couple of places, what it does not let me do is batch insert disparate models. 

For your second point, I do agree that bulk inserts for the same model will mostly be done under a different context than query batching. May be an enhancement request for activerecord-import.

**Comment by leoasis** [comment]
Sure, that would be the best place to suggest this. Hope this helped you at least a little!. Closing this one.
